import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:shorebird_cli/src/shorebird_env.dart';
import 'package:shorebird_cli/src/validators/validators.dart';

/// Checks that the project's `Runner.xcodeproj/project.pbxproj` does *not*
/// assign any `FLUTTER_`-prefixed build setting. Flutter itself populates
/// these at runtime or via the generated `Flutter/Generated.xcconfig` (which
/// we do not scan), so a hard-coded assignment in `project.pbxproj` can cause
/// different versions of Flutter to be used during different parts of the
/// build, potentially causing build failures.
///
/// `FLUTTER_TARGET` is exempted: it is commonly customized (e.g. to point at
/// a flavor-specific entrypoint like `lib/main_dev.dart`) and does not
/// participate in selecting which Flutter SDK is used.
///
/// Both standard Flutter apps (`ios/Runner.xcodeproj`) and Flutter modules
/// used for add-to-app (`.ios/Runner.xcodeproj`, generated by Flutter) are
/// covered.
class XcodeprojFlutterOverrideValidator extends Validator {
  static const _allowedOverrides = {'FLUTTER_TARGET'};

  @override
  String get description =>
      'Xcode project does not override FLUTTER_ build settings';

  @override
  Future<List<ValidationIssue>> validate() async {
    final root = shorebirdEnv.getFlutterProjectRoot();
    if (root == null) {
      return [];
    }

    final iosDir = _isFlutterModule() ? '.ios' : 'ios';
    final pbxprojRelativePath = p.join(
      iosDir,
      'Runner.xcodeproj',
      'project.pbxproj',
    );
    final pbxProjFile = File(p.join(root.path, pbxprojRelativePath));
    if (!pbxProjFile.existsSync()) {
      // No Xcode project to scan: a module that hasn't been `pub get`-ed yet,
      // an app without the iOS platform, or a non-Flutter project. Nothing
      // to validate.
      return [];
    }

    final overrides = _flutterOverridesIn(pbxProjFile);
    if (overrides.isEmpty) {
      return [];
    }

    final names = overrides.join(', ');
    return [
      ValidationIssue(
        severity: ValidationIssueSeverity.warning,
        message:
            '$pbxprojRelativePath overrides FLUTTER_ build setting(s): $names. '
            'FLUTTER_* variables are set by Flutter (at runtime or via '
            '$iosDir/Flutter/Generated.xcconfig) and should not be hard-coded '
            'in the Xcode project.',
      ),
    ];
  }

  /// Whether the current project is a Flutter module (i.e. its `pubspec.yaml`
  /// declares a `flutter > module` section). Modules expose their iOS Xcode
  /// project under `.ios/` rather than `ios/`.
  bool _isFlutterModule() {
    final pubspec = shorebirdEnv.getPubspecYaml();
    final module = pubspec?.flutter?['module'] as Map?;
    return module != null;
  }

  /// Returns the distinct set of `FLUTTER_*` names that are *assigned* in the
  /// given pbxproj contents (not merely referenced via `$(NAME)` or `$NAME`).
  Set<String> _flutterOverridesIn(File pbxProjFile) {
    // We could consider using package:xcode_parser, but for now this should
    // be sufficient.
    final contents = pbxProjFile.readAsStringSync();
    // Match FLUTTER_<NAME> assignments in various formats:
    // - FLUTTER_FOO = value;
    // - FLUTTER_FOO = "value";
    // - FLUTTER_FOO = $(FLUTTER_FOO);
    // Allow flexible spacing around the equals sign.
    // Use a negative lookahead on `//` to avoid line comments, and require
    // the assignment to terminate with `;` on the same line. Note: this does
    // not strip pbxproj `/* ... */` block comments, so a commented-out
    // assignment inside one would still be flagged. That's acceptable since
    // it still represents an intent to set FLUTTER_*.
    final matcher = RegExp(
      r'^(?!\s*//).*?(FLUTTER_\w+)\s*=\s*[^;\n]+;',
      multiLine: true,
    );
    return {
      for (final match in matcher.allMatches(contents))
        if (!_allowedOverrides.contains(match.group(1))) match.group(1)!,
    };
  }
}
