include: package:very_good_analysis/analysis_options.8.0.0.yaml
linter:
  rules:
    # Disabling in favor of the new Dart 3.7 format.
    # https://github.com/VeryGoodOpenSource/very_good_analysis/issues/136
    require_trailing_commas: false