# Validate with:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
# See https://docs.codecov.com/docs/flags
flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 99%
      - type: patch
        target: 100%
  individual_flags:
    - name: third_party
      paths:
        - third_party
      carryforward: true
      statuses:
        - type: project
          target: 85%
        - type: patch
          target: 100%
