# Validate with:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
# See https://docs.codecov.com/docs/flags

coverage:
  status:
    project:
      default:
        target: 98% #overall project/ repo coverage

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags:
    - name: packages
      paths:
        - packages
      carryforward: true
      statuses:
        - type: project
          target: 100%
        - type: patch
          target: 100%
    - name: third_party
      paths:
        - third_party
      carryforward: true
      statuses:
        - type: project
          target: 85%
        - type: patch
          target: 100%
