# Validate with:
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
# See https://docs.codecov.com/docs/flags
component_management:
  individual_components:
    - component_id: packages # this is an identifier that should not be changed
      name: packages # this is a display name, and can be changed freely
      paths:
        - packages/
    - component_id: third_party # this is an identifier that should not be changed
      name: third_party # this is a display name, and can be changed freely
      paths:
        - third_party/

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
