# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/packages/artifact_proxy"
    schedule:
      interval: "weekly"
    groups:
      artifact_proxy-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/discord_gcp_alerts"
    schedule:
      interval: "weekly"
    groups:
      discord_gcp_alerts-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/jwt"
    schedule:
      interval: "weekly"
    groups:
      jwt-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/redis_client"
    schedule:
      interval: "weekly"
    groups:
      redis_client-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/scoped"
    schedule:
      interval: "weekly"
    groups:
      scoped-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/shorebird_cli"
    schedule:
      interval: "weekly"
    groups:
      shorebird_cli-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/shorebird_code_push_client"
    schedule:
      interval: "weekly"
    groups:
      shorebird_code_push_client-deps:
        patterns:
          - "*"
  - package-ecosystem: "pub"
    directory: "/packages/shorebird_code_push_protocol"
    schedule:
      interval: "weekly"
    groups:
      shorebird_code_push_protocol-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gh-deps:
        patterns:
          - "*"
