name: flutter_version_resolver
description: A Dart tool that resolves a Flutter version for a given Flutter application
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.8.1

dependencies:
  cli_io:
    path: ../cli_io
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3

dev_dependencies:
  mocktail: ^1.0.5
  test: ^1.31.0
