[package]
name = "updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# "lib" is used by the "cli" target for testing from Rust
# "cdylib" is used by the "dart_cli" target for testing from Dart
# "staticlib" is used by the engine build for linking into libflutter.so
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
# Used for exposing C API
libc = "0.2.98"
# Used for networking.
reqwest = { version = "0.11",  default-features = false, features = ["blocking", "json", "rustls-tls"] }
# Json serialization/de-serialization.
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
# Used for error handling.
anyhow = {version = "1.0.69", features = ["backtrace"]}
# For error!(), info!(), etc macros. `print` will not show up on Android.
log = "0.4.14"
once_cell = "1.17.1"
serde_yaml = "0.9.19"
uuid = { version = "1.3.0", features = ["v4", "fast-rng", "macro-diagnostics", "serde"]}
sha2 = "0.10.6"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.13.0"
log-panics = { version = "2", features = ["with-backtrace"]}


[dev-dependencies]
tempdir = "0.3.7"
