name: cloud_logger
description: A Dart library for cloud logging
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.17.1
  shelf: ^1.4.0
  stack_trace: ^1.11.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
