name: dart_bindings
description: dart bindings for Shorebird updater library
version: 1.0.0

environment:
  sdk: '>=2.19.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  ffi: ^2.0.1
  # path version must match that depended on by Flutter SDK.
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
