engine_mappings:
  ff32625d5bda6d3eb2eb131e30a4c26ed4960002:
    flutter_engine_revision: ec975089acb540fc60752606a3d3ba809dd1528b
    shorebird_storage_bucket: download.shorebird.dev
    shorebird_artifact_overrides:
      - flutter_infra_release/flutter/$engine/android-x64-release/artifacts.zip
      - download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-$engine/flutter_embedding_release-1.0.0-$engine.pom
      - download.flutter.io/io/flutter/flutter_embedding_release/1.0.0-$engine/flutter_embedding_release-1.0.0-$engine.jar
      - download.flutter.io/io/flutter/arm64_v8a_release/1.0.0-$engine/arm64_v8a_release-1.0.0-$engine.pom
      - download.flutter.io/io/flutter/arm64_v8a_release/1.0.0-$engine/arm64_v8a_release-1.0.0-$engine.jar
