name: Pana Workflow

inputs:
  min_score:
    required: false
    type: number
    default: 120
  pana_version:
    required: false
    type: string
  working_directory:
    required: false
    type: string
    default: "."

runs:
  using: "composite"
  steps:
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: flutter pub global activate pana ${{inputs.pana_version}}

    - working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: |
        PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
        echo "Score: $PANA_SCORE"
        IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0];
        if (( $SCORE < ${{inputs.min_score}} )); then echo "The minimum score of ${{inputs.min_score}} was not met!"; exit 1; fi
