import 'package:path/path.dart' as p;
import 'package:scoped/scoped.dart';
import 'package:shorebird_cli/src/command.dart';
import 'package:shorebird_cli/src/third_party/flutter_tools/lib/flutter_tools.dart';

/// Thrown when multiple artifacts are found in the build directory.
class MultipleArtifactsFoundException implements Exception {
  MultipleArtifactsFoundException({
    required this.buildDir,
    required this.foundArtifacts,
  });

  final String buildDir;
  final List<FileSystemEntity> foundArtifacts;

  @override
  String toString() {
    return 'Multiple artifacts found in $buildDir: '
        '${foundArtifacts.map((e) => e.path)}';
  }
}

/// Thrown when no artifact is found in the build directory.
class ArtifactNotFoundException implements Exception {
  ArtifactNotFoundException({
    required this.artifactName,
    required this.buildDir,
  });

  final String artifactName;
  final String buildDir;

  @override
  String toString() {
    return 'Artifact $artifactName not found in $buildDir';
  }
}

/// When building android artifacts, gradlew name these artifacts in a non
/// consistent way.
///
/// Example:
///
///  ## AABs
///  Without flavors
///  ...bundle/release/app-release.aab
///
///  With flavors
///  ...bundle/flavor/app-flavor-release.aab
///
///  With multi dimensional flavors
///  ...bundle/fullFlavorCamelCase/app-flavor1-flavor2-release.aab
///
/// The pattern follows for APKs.
///
/// The only thing that is consistent is the artifactId which is the name of the
/// artifact will follow always the same order of name of the flavors.
///
/// So we create the idea of an identifier, which consistis in the file name
/// without any special character and in lower case, that allows use to easily
/// search in the build folder what was the artifact that was generated by the
/// flutter build command.
extension on String {
  String get artifactId => replaceAll(RegExp(r'\W'), '').toLowerCase();
}

final shorebirdAndroidArtifactsRef = create(ShorebirdAndroidArtifacts.new);

ShorebirdAndroidArtifacts get shorebirdAndroidArtifacts =>
    read(shorebirdAndroidArtifactsRef);

/// Mixin on [ShorebirdCommand] which exposes methods
// to find the artifacts generated for android
class ShorebirdAndroidArtifacts {
  /// Find the artifact in the build directory.
  String _findArtifact({
    required String artifactName,
    required String buildDir,
  }) {
    // Remove all non characters and digits from the artifact name.
    final artifactId = artifactName.artifactId;

    final directory = Directory(buildDir);
    if (!directory.existsSync()) {
      throw ArtifactNotFoundException(
        artifactName: artifactName,
        buildDir: buildDir,
      );
    }

    final allFiles = directory.listSync();
    final candidates = allFiles.where((file) {
      final fileName = p.basename(file.path);
      return fileName.artifactId == artifactId;
    }).toList();

    if (candidates.isEmpty) {
      throw ArtifactNotFoundException(
        artifactName: artifactName,
        buildDir: buildDir,
      );
    }

    if (candidates.length > 1) {
      throw MultipleArtifactsFoundException(
        buildDir: buildDir,
        foundArtifacts: candidates,
      );
    }

    return candidates.first.path;
  }

  /// Find the app bundle in the build directory.
  String findAppBundle({
    required String projectPath,
    required String? flavor,
  }) {
    final buildDir = p.join(
      projectPath,
      'build',
      'app',
      'outputs',
      'bundle',
      flavor != null ? '${flavor}Release' : 'release',
    );

    final artifactName =
        flavor == null ? 'app-release.aab' : 'app-$flavor-release.aab';

    return _findArtifact(
      buildDir: buildDir,
      artifactName: artifactName,
    );
  }

  /// Find the apk in the build directory.
  String findApk({
    required String projectPath,
    required String? flavor,
  }) {
    final buildDir = p.join(
      projectPath,
      'build',
      'app',
      'outputs',
      'flutter-apk',
    );

    final artifaceName =
        flavor == null ? 'app-release.apk' : 'app-$flavor-release.apk';

    return _findArtifact(
      buildDir: buildDir,
      artifactName: artifaceName,
    );
  }
}
