analyzer:
  errors:
    file_names: ignore
    prefer_constructors_over_static_methods: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
