name: Verify Version Workflow

inputs:
  ssh_key:
    required: false
    type: string
    default: ""
  working_directory:
    required: false
    type: string
    default: "."

runs:
  using: "composite"

  steps:
    - name: 📚 Git Checkout
      uses: actions/checkout@v3

    - name: 🎯 Setup Dart
      uses: dart-lang/setup-dart@v1

    - name: 🤖 Configure SSH Agent
      working-directory: ${{ inputs.working_directory }}
      if: ${{ inputs.ssh_key != ''}}
      shell: ${{ inputs.shell }}
      run: |
        eval `ssh-agent -s`
        ssh-add - <<< '${{ inputs.ssh_key }}'

    - name: 📦 Install Dependencies
      shell: ${{ inputs.shell }}
      run: dart pub get
      working-directory: ${{ inputs.working_directory }}

    - name: 🔎 Verify version
      shell: ${{ inputs.shell }}
      run: dart run test --run-skipped -t version-verify
      working-directory: ${{ inputs.working_directory }}
