[package]
name = "shorebird_code_push_updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# Build a rust library (for testing with rust "cli" project) and a c library
crate-type = ["staticlib"]

[dependencies]
# Used for exposing C API
libc = "0.2.98"
# Used for networking.
reqwest = { version = "0.11",  default-features = false, features = ["blocking", "json", "rustls-tls"] }
# Json serialization/de-serialization.
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.93"
# Used for creating custom errors.
thiserror = "1.0"
# Used for error handling.
anyhow = {version = "1.0.69", features = ["backtrace"]}
# Used for logging.
android_logger = "0.13.0"
log = "0.4.14"
