import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Detects Android plugins that still reference the legacy `flutter.jar`
/// Flutter engine artifact.
///
/// `flutter.jar` lived at `bin/cache/artifacts/engine/android-arm/flutter.jar`
/// in the Flutter v1 Android embedding and was removed in Flutter 1.12. Modern
/// Flutter ships the Android engine as Maven artifacts, so the file never
/// exists in a current cache. A plugin whose `android/build.gradle` still
/// declares a file dependency on it (an outdated `huawei_location`, for
/// example) fails with an opaque Gradle error like
/// "File/directory does not exist ... /android-arm/flutter.jar".
///
/// Shorebird builds every ABI (including 32-bit `android-arm`) by default, so
/// this can surface under `shorebird release` even when a developer's own
/// `flutter build` (often arm64-only) does not, which is the confusing
/// "flutter build works but shorebird fails" symptom.
///
/// See https://github.com/shorebirdtech/shorebird/issues/3783.
abstract final class LegacyFlutterJarReference {
  /// The substring that identifies a reference to the legacy artifact in a
  /// Gradle build file.
  static const _marker = 'flutter.jar';

  /// Returns the names of resolved Android plugins under [projectRoot] whose
  /// Gradle build files reference the legacy `flutter.jar` artifact.
  ///
  /// Reads the plugin list from `.flutter-plugins-dependencies` (generated by
  /// `flutter pub get`). Returns an empty list when that file is absent or no
  /// plugin matches. Never throws, so it is safe to call while already
  /// handling a build failure.
  static List<String> findInProject(Directory projectRoot) {
    final names = <String>[];
    try {
      final manifest = File(
        p.join(projectRoot.path, '.flutter-plugins-dependencies'),
      );
      if (!manifest.existsSync()) return names;

      final decoded =
          jsonDecode(manifest.readAsStringSync()) as Map<String, dynamic>;
      final plugins = decoded['plugins'] as Map<String, dynamic>?;
      final androidPlugins = plugins?['android'] as List<dynamic>?;
      if (androidPlugins == null) return names;

      for (final entry in androidPlugins.whereType<Map<String, dynamic>>()) {
        final name = entry['name'] as String?;
        final path = entry['path'] as String?;
        if (name == null || path == null) continue;
        if (_referencesLegacyJar(path)) names.add(name);
      }
    } on Object {
      // Best-effort diagnostic: a malformed manifest or unreadable file must
      // never mask the underlying build failure.
      return names;
    }
    return names;
  }

  /// Whether either Gradle build file under the plugin at [pluginPath]
  /// references the legacy artifact.
  static bool _referencesLegacyJar(String pluginPath) {
    for (final fileName in const ['build.gradle', 'build.gradle.kts']) {
      final gradleFile = File(p.join(pluginPath, 'android', fileName));
      if (!gradleFile.existsSync()) continue;
      if (gradleFile.readAsStringSync().contains(_marker)) return true;
    }
    return false;
  }

  /// A fix recommendation naming the offending [pluginNames], suitable for
  /// prepending to the generic build-failure recommendation.
  static String recommendation(List<String> pluginNames) {
    final bullets = pluginNames.map((name) => '  • $name').join('\n');
    return '''

💡 A plugin in your project references the legacy `flutter.jar` Flutter engine
artifact, which was removed in Flutter 1.12 and does not exist in modern
Flutter versions. This is what produces the Gradle error
"File/directory does not exist ... /android-arm/flutter.jar".

Upgrade the following plugin(s) to a version that supports your Flutter
version, or remove the `flutter.jar` reference from their Android build files.

$bullets
''';
  }
}
