name: Rust Crate Workflow
description: Build and Test your rust crate

inputs:
  working_directory:
    required: false
    default: "."
    description: The working directory for this workflow.

runs:
  using: "composite"
  steps:
    - name: Build
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: cargo build --verbose

    - name: Test
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: cargo test --verbose
