name: Rust Crate Workflow

inputs:
  working_directory:
    required: false
    type: string
    default: "."

runs:
  using: "composite"
  steps:
    - name: Build
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: cargo build

    - name: Test
      working-directory: ${{ inputs.working_directory }}
      shell: ${{ inputs.shell }}
      run: cargo test
