name: shorebird_process_tools
description: Helpers for interacting with system utilities (e.g., git)
version: 0.1.0
repository: https://github.com/shorebirdtech/shorebird
resolution: workspace

publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  scoped_deps: ^0.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
